(() => {
  'use strict'; const $=s=>document.querySelector(s),app=$('#app');let role='admin',cloudOrders=null;
  const labels={new:'جديد',accepted:'مقبول',preparing:'قيد التجهيز',ready:'جاهز للاستلام',delivering:'مع المندوب',delivered:'تم التسليم',cancelled:'ملغي'};
  const safe=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','>':'&gt;','<':'&lt;',"'":'&#39;','"':'&quot;'}[c])); const time=v=>new Date(v).toLocaleString('ar-EG',{hour:'numeric',minute:'2-digit',day:'numeric',month:'short'});
  function row(o,actions=''){return `<tr><td><b>${safe(o.reference)}</b><small style="display:block;color:#69736e">${time(o.createdAt)}</small></td><td>${safe(o.customer.name)}<small style="display:block;color:#69736e">${safe(o.customer.phone)}</small></td><td>${o.total} ج.م</td><td><span class="tag ${o.status}">${labels[o.status]}</span></td><td>${actions}</td></tr>`}
  function table(orders,fn){return orders.length?`<div style="overflow:auto"><table class="table"><thead><tr><th>الطلب</th><th>العميل</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${orders.map(fn).join('')}</tbody></table></div>`:'<div class="empty">لا توجد طلبات في هذه المرحلة.</div>'}
  function admin(d){const active=d.orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length;return `<div class="metrics"><div class="metric"><small>طلبات نشطة</small><b>${active}</b></div><div class="metric"><small>شركاء مفعلون</small><b>${d.stores.filter(x=>x.status==='active').length}</b></div><div class="metric"><small>مندوبون متاحون</small><b>${d.riders.filter(x=>x.status==='available').length}</b></div><div class="metric"><small>إجمالي اليوم</small><b>${d.orders.reduce((n,o)=>n+o.total,0)} ج.م</b></div></div><div class="split"><section class="panel"><h2>أحدث الطلبات</h2>${table(d.orders.slice(0,8),o=>row(o,o.status==='new'?`<button class="action" data-set="accepted" data-id="${o.id}">قبول</button>`:'—'))}</section><section class="panel"><h2>طلبات انضمام الشركاء</h2><ul class="list">${d.stores.map(s=>`<li><span>${s.type==='pharmacy'?'💊':'🛒'}</span><div><b>${safe(s.name)}</b><small>${safe(s.area)}</small></div><span style="margin-inline-start:auto">${s.status==='pending'?`<button class="action red" data-store="${s.id}">تفعيل</button>`:'<span class="tag delivered">مفعّل</span>'}</span></li>`).join('')}</ul></section></div>`}
  function merchant(d){const orders=d.orders.filter(o=>!['delivered','cancelled'].includes(o.status));return `<div class="metrics"><div class="metric"><small>طلبات جديدة</small><b>${orders.filter(o=>o.status==='new').length}</b></div><div class="metric"><small>قيد التجهيز</small><b>${orders.filter(o=>o.status==='preparing').length}</b></div><div class="metric"><small>جاهزة للاستلام</small><b>${orders.filter(o=>o.status==='ready').length}</b></div><div class="metric"><small>مبيعات معلقة</small><b>${orders.reduce((n,o)=>n+o.total,0)} ج.م</b></div></div><section class="panel"><h2>طلبات المتجر</h2>${table(orders,o=>{const n=o.status==='new'?'accepted':o.status==='accepted'?'preparing':o.status==='preparing'?'ready':null;return row(o,n?`<button class="action" data-set="${n}" data-id="${o.id}">${n==='accepted'?'تأكيد':n==='preparing'?'ابدأ التجهيز':'جاهز للمندوب'}</button>`:'—')})}</section>`}
  function rider(d){const mine=d.orders.filter(o=>o.riderId==='rider-1'||(o.status==='ready'&&!o.riderId));return `<div class="metrics"><div class="metric"><small>حالة المندوب</small><b style="font-size:1rem;color:#0a8150">متاح الآن</b></div><div class="metric"><small>طلبات للاستلام</small><b>${mine.filter(o=>o.status==='ready').length}</b></div><div class="metric"><small>قيد التوصيل</small><b>${mine.filter(o=>o.status==='delivering').length}</b></div><div class="metric"><small>تم اليوم</small><b>${d.orders.filter(o=>o.status==='delivered').length}</b></div></div><section class="panel"><h2>رحلاتي</h2>${table(mine,o=>row(o,o.status==='ready'?`<button class="action" data-pick="${o.id}">استلام</button>`:o.status==='delivering'?`<button class="action red" data-set="delivered" data-id="${o.id}">تم التسليم</button>`:'—'))}</section>`}
  function customer(d){return `<section class="panel"><h2>متابعة الطلبات</h2><p style="color:#69736e;font-size:.82rem">بعد إرسال الطلب من المتجر سيظهر هنا على نفس الجهاز. عند ربط Firebase ستكون المتابعة متاحة من أي جهاز برقم الهاتف.</p>${table(d.orders.slice(0,10),o=>row(o,'—'))}</section>`}
  function render(){const d=ACDPlatform.read();if(cloudOrders)d.orders=cloudOrders;const notes={admin:'واجهة مركزية: قبول شركاء، تعيين المندوبين، ومتابعة كل الطلبات.',merchant:'واجهة صاحب المحل: يؤكد الطلب ثم يجهزه للاستلام.',rider:'واجهة المندوب: يستلم الطلب الجاهز ويغيّر حالته حتى التسليم.',customer:'واجهة العميل: يتابع حالة طلبه خطوة بخطوة.'};$('#modeNote').textContent=notes[role];app.innerHTML=role==='admin'?admin(d):role==='merchant'?merchant(d):role==='rider'?rider(d):customer(d)}
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='loginBtn'){try{if(ACDCloud.user())await ACDCloud.signOut();else await ACDCloud.signIn()}catch(_){alert('تعذر تسجيل الدخول الآن.')}return}if(b.dataset.role){role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===b));render()}if(b.dataset.set){if(window.ACDCloud&&ACDCloud.user())await ACDCloud.updateOrder(b.dataset.id,{status:b.dataset.set});else ACDPlatform.updateOrder(b.dataset.id,{status:b.dataset.set});render()}if(b.dataset.pick){if(window.ACDCloud&&ACDCloud.user())await ACDCloud.updateOrder(b.dataset.pick,{status:'delivering',riderId:ACDCloud.user().uid});else ACDPlatform.updateOrder(b.dataset.pick,{status:'delivering',riderId:'rider-1'});render()}if(b.dataset.store){const d=ACDPlatform.read(),s=d.stores.find(x=>x.id===b.dataset.store);if(s){s.status='active';ACDPlatform.write(d);render()}}});
  function cloudReady(){if(!window.ACDCloud)return;const u=ACDCloud.user();$('#loginBtn').textContent=u?'خروج '+(u.displayName||''):'تسجيل الدخول';if(u)ACDCloud.watchOrders(x=>{cloudOrders=x;render()});render()}window.addEventListener('acd-auth-change',cloudReady);window.addEventListener('acd-cloud-ready',cloudReady);window.addEventListener('acd-platform-change',render);window.addEventListener('storage',render);render();
})();
